resources:
  image_id: docker:ghcr.io/tufalabs/nyx:25.05-ubuntu24.04
  accelerators: B200:2
  cpus: 24
  memory: 192

setup: |
  echo "CHECKPOINTS_DIR=\"/mnt/checkpoints/${SKYPILOT_TASK_ID}/\"" >> /etc/environment
  echo "LOGS_DIR=\"/mnt/logs/${SKYPILOT_TASK_ID}/\"" >> /etc/environment
  echo "ARTIFACTS_DIR=\"/mnt/artifacts/${SKYPILOT_TASK_ID}/\"" >> /etc/environment

config:
  kubernetes:
    provision_timeout: 20
    pod_config:
      spec:
        nodeSelector:
          node-type: on-demand
        containers:
          - volumeMounts:
              - mountPath: /mnt/checkpoints
                name: nfs-checkpoints
              - mountPath: /mnt/logs
                name: nfs-logs
              - mountPath: /mnt/artifacts
                name: nfs-artifacts
              - mountPath: /mnt/builds
                name: nfs-builds
        volumes:
          - name: nfs-checkpoints
            nfs:
              server: 10.100.0.253
              path: /data/shared/checkpoints
              readOnly: false
          - name: nfs-logs
            nfs:
              server: 10.100.0.253
              path: /data/shared/logs
              readOnly: false
          - name: nfs-artifacts
            nfs:
              server: 10.100.0.253
              path: /data/shared/artifacts
              readOnly: false
          - name: nfs-builds
            nfs:
              server: 10.100.0.253
              path: /data/shared/builds
              readOnly: true
